
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showInputDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Trix
 */
public class Ventana extends javax.swing.JFrame {

    public MetodosOrdenamiento ordenar = new MetodosOrdenamiento();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Métodos de ordenamiento.");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBurbuja = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnShell = new javax.swing.JButton();
        btnRadix = new javax.swing.JButton();
        btnQuick = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnIntercalación = new javax.swing.JButton();
        btnMezcD = new javax.swing.JButton();
        btnMezcN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOri = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOri2 = new javax.swing.JTextArea();
        lblMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenerar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGenerar.setText("Generar datos");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tamaño del vector:");

        txtTamaño.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Métodos de ordenamiento");

        btnBurbuja.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBurbuja.setText("Burbuja");
        btnBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurbujaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Ordenamiento interno");

        btnShell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnShell.setText("ShellSort");
        btnShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShellActionPerformed(evt);
            }
        });

        btnRadix.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRadix.setText("Radix");
        btnRadix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadixActionPerformed(evt);
            }
        });

        btnQuick.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnQuick.setText("Quicksort");
        btnQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ordenamiento externo");

        btnIntercalación.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnIntercalación.setText("Intercalación");
        btnIntercalación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntercalaciónActionPerformed(evt);
            }
        });

        btnMezcD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMezcD.setText("Mezcla Directa");
        btnMezcD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezcDActionPerformed(evt);
            }
        });

        btnMezcN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMezcN.setText("Mezcla Natural");
        btnMezcN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezcNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ordenamiento:");

        txtOri.setEditable(false);
        txtOri.setColumns(20);
        txtOri.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtOri.setRows(5);
        jScrollPane1.setViewportView(txtOri);

        txtOri2.setEditable(false);
        txtOri2.setColumns(20);
        txtOri2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtOri2.setRows(5);
        jScrollPane2.setViewportView(txtOri2);

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Valores ordenados");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Valores originales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTamaño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnQuick, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRadix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShell, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBurbuja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMezcD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(btnIntercalación, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMezcN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnShell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadix)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnQuick)
                            .addComponent(btnMezcN)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIntercalación)
                            .addComponent(jLabel5)
                            .addComponent(btnBurbuja))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnMezcD))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int vector[] = new int [0];
    int vector2[];
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try {

            int i = Integer.parseInt(txtTamaño.getText());
            int m1[] = new int[i];
            String cad = "", cad0 = "Lista de valores original: \n";
            for (int u = 0; u < i; u++) {
                m1[u] = (int) (Math.random() * 50 + 1);
                cad += "[" + m1[u] + "]";
            }
            cad += "\n";
            txtOri.append(cad0 + cad + "\n");
            setTitle("Datos generados: " + txtTamaño.getText());
            vector = m1;
        } catch (java.lang.NumberFormatException error1) {
            showMessageDialog(null, "Ingrese un dígito válido.");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed


    private void btnBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurbujaActionPerformed
        try {
            String cad = "Ordenados por método de burbuja:";
            txtOri2.append(cad + "\n" + ordenar.Burbuja(vector) + "\n");
            lblMensaje.setText("Burbuja");
        } catch (java.lang.NullPointerException error1) {
            showMessageDialog(null, "Primero debe generar dígitos.");
        }
    }//GEN-LAST:event_btnBurbujaActionPerformed

    private void btnShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShellActionPerformed
        try {
            String cad="Ordenados por método de ShellSort:";
            txtOri2.append(cad+"\n"+ordenar.Shell(vector) + "\n");
            lblMensaje.setText("SellSort");
        } catch (java.lang.NullPointerException error1) {
            showMessageDialog(null, "Primero debe generar dígitos.");
        }
    }//GEN-LAST:event_btnShellActionPerformed

    private void btnRadixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadixActionPerformed
        try {
            String cad="Ordenados por método de Radix:";
            txtOri2.append(cad+"\n"+ordenar.Radix(vector) + "\n");
            lblMensaje.setText("Radix");
        } catch (java.lang.NullPointerException error1) {
            showMessageDialog(null, "Primero debe generar dígitos.");

        }
    }//GEN-LAST:event_btnRadixActionPerformed

    private void btnQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickActionPerformed
        try {
            int x = vector.length - 1;
            System.out.println("Proceso Quicksort:");
            String cad="Ordenados por método Quicksort:\n";
            txtOri2.append(cad+"\n"+ordenar.quick(vector, 0, x) + "\n");
            lblMensaje.setText("Quicksort");
        } catch (java.lang.NullPointerException error1) {
            showMessageDialog(null, "Primero debe generar dígitos.");
        }
    }//GEN-LAST:event_btnQuickActionPerformed
    public String generarMatriz(int i) {
        int m1[] = new int[i];
        String cad = "";
        for (int u = 0; u < i; u++) {
            m1[u] = (int) (Math.random() * 50 + 1);
            cad += "[" + m1[u] + "]";
        }
        cad += "\n";
        return cad;
    }

    private void btnIntercalaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntercalaciónActionPerformed
           
        try {
            int y = Integer.parseInt(showInputDialog(this, "Ingrese el tamño del vector para Intercalación: "));

            int m1[] = new int[y];
            String cad = "", cad0 = "Lista de valores original: \n";
            for (int u = 0; u < y; u++) {
                m1[u] = (int) (Math.random() * 50 + 1);
                cad += "[" + m1[u] + "]";
            }
            cad += "\n";
            vector2 = m1;

            txtOri.append("Matriz generada para Intercalación\n" + cad + "\n");
            txtOri.append("Vector original ordenado:\n" + ordenar.Burbuja(vector) + "\n");
            txtOri.append("Vector auxiliar ordenado:\n" + ordenar.Burbuja(vector2) + "\n");
            txtOri2.append("Ordenados por método de Intercalación:\n" + ordenar.Intercalacion(vector, vector2) + "\n");
            lblMensaje.setText("Intercalación");

        } catch (java.lang.NullPointerException error1) {
            showMessageDialog(null, "Primero debe generar dígitos.");
        } catch (java.lang.NumberFormatException error2) {
            showMessageDialog(null, "Ingrese un valor del vector a intercalar.");
        }
    
    }//GEN-LAST:event_btnIntercalaciónActionPerformed

    private void btnMezcDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezcDActionPerformed
        try {
            String cad="Ordenador por mezcla directa:";
            txtOri2.append(cad+"\n"+Hmostring(ordenar.mezclaDirecta(vector)) + "\n");
            lblMensaje.setText("Mezcla directa");
        } catch (java.lang.NullPointerException error1) {
            showMessageDialog(null, "Primero debe generar dígitos.");
        } catch (java.lang.NumberFormatException error2) {
            showMessageDialog(null, "Ingrese un valor del vector a intercalar.");
        }
    }//GEN-LAST:event_btnMezcDActionPerformed

    private void btnMezcNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezcNActionPerformed
        try {
            String cad="Ordenador por mezcla natural:";
            ordenar.mezclaNatural(vector);
            txtOri2.append(cad+"\n"+Hmostring(ordenar.mezclaNatural(vector)) + "\n");
            lblMensaje.setText("Mezcla natural");
        } catch (java.lang.NullPointerException error1) {
            showMessageDialog(null, "Primero debe generar dígitos.");
        } catch (java.lang.NumberFormatException error2) {
            showMessageDialog(null, "Ingrese un valor del vector a intercalar.");
        }
    }//GEN-LAST:event_btnMezcNActionPerformed

    public String Hmostring(int[] numeros) {
        int k = 0;
        String cad = "";
        for (k = 0; k < numeros.length; k++) {
            cad += "[" + numeros[k] + "]";
        }
        cad += "\n";
        return cad;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtOri2.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtOri.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBurbuja;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnIntercalación;
    private javax.swing.JButton btnMezcD;
    private javax.swing.JButton btnMezcN;
    private javax.swing.JButton btnQuick;
    private javax.swing.JButton btnRadix;
    private javax.swing.JButton btnShell;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextArea txtOri;
    private javax.swing.JTextArea txtOri2;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
